// One MSW worker for the whole Browser Mode run. Its lifecycle (start / reset /
// stop) is wired in vitest.setup.ts.
//
// Browser Mode runs the tests inside a real Chromium, so requests are
// intercepted by a Service Worker (`msw/browser`) instead of by Node's http
// layer (`msw/node`). The worker script itself lives in
// public/mockServiceWorker.js and is generated by the `postinstall` script
// (`msw init public/`).
import { setupWorker } from "msw/browser";
import { handlers as accountHandlers } from "@account/mocks/handlers";
import { handlers as activityHandlers } from "@activity/mocks/handlers";

// Every vertical's default handlers, in one worker. A vertical that has its own
// API surface registers it here; `worker.use(...)` inside a test still wins over
// whatever this list installed.
export const worker = setupWorker(...accountHandlers, ...activityHandlers);
