// One MSW worker for the whole Browser Mode run. Its lifecycle (start / reset /
// stop) is wired in vitest.setup.ts.
//
// Browser Mode runs the tests inside a real Chromium, so requests are
// intercepted by a Service Worker (`msw/browser`) instead of by Node's http
// layer (`msw/node`). The worker script itself lives in
// public/mockServiceWorker.js and is generated by the `postinstall` script
// (`msw init public/`).
import { setupWorker } from "msw/browser";
import { handlers } from "@account/mocks/handlers";

export const worker = setupWorker(...handlers);
