/**
 * The connection, and the migrations that run before anything uses it.
 *
 * Migrations are generated by `yarn db:generate` (drizzle-kit, from schema.ts
 * into migrations/), committed, and applied here when the API starts: a fresh
 * database is brought up to date by the process that needs it, and one already
 * at the current version is left alone. Drizzle records what it has applied in
 * its own `__drizzle_migrations` table, so a restart is a no-op.
 *
 * The URL comes from DATABASE_URL, documented in .env.example. Locally that is
 * the Postgres from compose.yaml; in CI it is the job's `postgres` service.
 */
import { fileURLToPath } from "node:url";
import { drizzle, type NodePgDatabase } from "drizzle-orm/node-postgres";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { Pool } from "pg";

/** Shared with the unit tests, which apply the same migrations to PGlite. */
export const MIGRATIONS_FOLDER = fileURLToPath(new URL("./migrations", import.meta.url));

export async function connect(): Promise<NodePgDatabase> {
  const url = process.env.DATABASE_URL;
  if (!url) {
    throw new Error("DATABASE_URL is not set; see .env.example");
  }

  const db = drizzle({ client: new Pool({ connectionString: url }) });
  await migrate(db, { migrationsFolder: MIGRATIONS_FOLDER });
  return db;
}
