// One MSW worker for the whole Browser Mode run. Its lifecycle (start / reset /
// stop) is wired in vitest.setup.ts, which is also where it is CREATED, and
// with which handlers.
//
// It used to import the account's handlers directly, which made this folder
// depend on a vertical while every vertical's tests depend on this folder -
// fine as one source tree, a cycle as soon as they are packages. The handlers
// now arrive from the setup file, so ./app-under-test's rule holds here too:
// nothing in testing/ reaches into the app.
//
// Deliberately still ONE instance rather than one per file: `worker.use(...)`
// in a test adds an override that `resetHandlers()` drops after it, and both
// only mean anything against the worker the setup file started. Passing the
// handlers to `setupWorker` rather than `use`-ing them afterwards is what
// makes them the list `resetHandlers()` returns to.
//
// Browser Mode runs the tests inside a real Chromium, so requests are
// intercepted by a Service Worker (`msw/browser`) instead of by Node's http
// layer (`msw/node`). The worker script itself lives in
// public/mockServiceWorker.js and is generated by the `postinstall` script
// (`msw init public/`).
import { setupWorker, type SetupWorker } from "msw/browser";
import type { RequestHandler } from "msw";

let instance: SetupWorker | null = null;

/** Called once, by vitest.setup.ts, before any test file runs. */
export function createWorker(handlers: RequestHandler[]): SetupWorker {
  instance = setupWorker(...handlers);
  return instance;
}

/** The worker the setup file created, for a test that overrides a response. */
export function worker(): SetupWorker {
  if (!instance) {
    throw new Error("No MSW worker: vitest.setup.ts has to call createWorker() first.");
  }

  return instance;
}
